#!/command/with-contenv /bin/sh
# Reads SAIL_LOG_MODE / SAIL_LOG_MAX_ARCHIVES / SAIL_LOG_ROTATE_SIZE at exec
# time so this file never needs to be rewritten at boot (compatible with
# readOnlyRootFilesystem pods).
ARCHIVES="${SAIL_LOG_MAX_ARCHIVES:-20}"
SIZE="${SAIL_LOG_ROTATE_SIZE:-10000000}"
case "${SAIL_LOG_MODE:-both}" in
  stdout) exec s6-log -b n${ARCHIVES} s${SIZE} T !"gzip -nq9" p[nginx] 1 ;;
  file)   exec s6-log -b n${ARCHIVES} s${SIZE} T !"gzip -nq9" /var/log/nginx p[nginx] ;;
  both)   exec s6-log -b n${ARCHIVES} s${SIZE} T !"gzip -nq9" /var/log/nginx p[nginx] 1 ;;
  *)      echo "nginx-log: invalid SAIL_LOG_MODE='${SAIL_LOG_MODE}' (expected stdout|file|both)" >&2; exit 1 ;;
esac
