<?php

namespace Laravel\Sail\Console\Concerns;

use Illuminate\Support\Str;
use Symfony\Component\Process\Process;
use Symfony\Component\Yaml\Yaml;

trait InteractsWithHelm
{
    protected string $projectName;

    protected string $helmPath;

    /**
     * Whether values.yaml was freshly created from the stub during this run.
     *
     * A freshly created file may be fully generated; a pre-existing file is
     * consumer-owned and must be preserved (values and comments alike).
     */
    protected bool $valuesFileCreated = false;

    /**
     * Free-form Kubernetes maps that are consumer-owned once they exist.
     *
     * When the consumer's values.yaml already contains one of these maps,
     * stub defaults are never merged into it (e.g. opinionated ingress
     * annotations like a Traefik certresolver must not be injected).
     *
     * @var array<int, string>
     */
    protected array $consumerOwnedMapKeys = [
        'annotations',
        'podAnnotations',
        'labels',
        'nodeSelector',
        'tolerations',
    ];

    /**
     * Build the Docker Compose file.
     *
     * @param  bool  $updateVersion  Whether to update the chart version (default: true)
     * @return void
     */
    protected function buildHelm(bool $updateVersion = true)
    {
        $this->output->writeln('');
        $this->components->info('📦 Preparing Helm Chart...');
        $this->output->writeln('');
        $this->projectName = config('app.name', 'laravel');
        $this->createHelmDirectory();

        // Update chart (version update controlled by parameter)
        $this->buildHelmChart($updateVersion);

        $this->buildHelmValues($updateVersion);

        // Validate Helm chart
        $this->validateHelmChart();

        $this->output->writeln('');
        $this->components->info('✅ Helm Chart Created Successfully!');
        $this->output->writeln('');
    }

    /**
     * Validate the Helm chart using helm lint.
     */
    protected function validateHelmChart(): void
    {
        $this->output->writeln('  <bg=blue;fg=black> INFO </> Validating Helm chart...');

        $process = new Process(['helm', 'lint', $this->helmPath]);
        $process->run();

        if (! $process->isSuccessful()) {
            $this->output->writeln('');
            $this->components->error('Helm chart validation failed!');
            $this->output->writeln($process->getErrorOutput());
            $this->components->warn('💡 Tip: Review the errors above and fix any issues in your Helm templates.');
            $this->output->writeln('');
        } else {
            $this->output->writeln('  <fg=green>✓</> Helm chart validation passed');
        }
    }

    /**
     * Create the Helm Chart directory.
     */
    protected function createHelmDirectory(): string
    {
        $this->helmPath = base_path('helm');

        $stubPath = realpath(__DIR__.'/../../../stubs/helm');
        $chart = $this->copyFiles($stubPath, $this->helmPath);

        $templatePath = realpath($stubPath.'/templates');
        $installTemplatePath = $this->helmPath.'/templates';
        $templates = $this->copyFiles($templatePath, $installTemplatePath);

        if ($chart || $templates) {
            $this->output->writeln('  <bg=blue;fg=black> INFO </> Helm Chart files copied successfully.');
        } else {
            $this->output->writeln('  <bg=blue;fg=black> INFO </> No changes made to the Helm Chart files.');
        }

        $this->createValuesOverrideFile();

        $this->output->writeln('');

        return $this->helmPath;
    }

    /**
     * Create the values override file if it doesn't exist.
     *
     * This file is user-owned and never overwritten by sail:build.
     * It's passed as a second -f flag during helm upgrade so user
     * customizations (ingress annotations, resource overrides, etc.)
     * survive chart regeneration.
     */
    protected function createValuesOverrideFile(): void
    {
        $overridePath = $this->helmPath.'/values.production.yaml';

        if (is_file($overridePath)) {
            return;
        }

        $content = <<<'YAML'
# ==============================================================================
# Production Value Overrides
# ==============================================================================
# This file is YOUR configuration — sail:build will never overwrite it.
#
# values.yaml is regenerated by sail:build on every run. Any customizations
# you make there (ingress annotations, resource limits, replica counts, etc.)
# will be lost on the next build.
#
# Put all environment-specific overrides here instead. During deploy, pass
# both files to Helm:
#
#   helm upgrade <release> <chart> -f values.yaml -f values.production.yaml
#
# The second file wins for any overlapping keys.
# ==============================================================================

# Example overrides (uncomment and customize as needed):
#
# resources:
#   limits:
#     cpu: "2"
#     memory: 2Gi
#
# ingress:
#   annotations:
#     traefik.ingress.kubernetes.io/router.middlewares: default-security-headers@kubernetescrd
#
# web:
#   replicaCount: 3
YAML;

        file_put_contents($overridePath, $content);
        $this->output->writeln('  <fg=green>✓</> Created values.production.yaml (user-owned overrides — never overwritten by sail:build)');
    }

    protected function copyFiles(string $path_from, string $path_to): bool
    {
        $changes = false;

        if (! is_dir($path_to)) {
            mkdir($path_to, 0755, true);
        }

        $files = scandir($path_from);
        foreach ($files as $file) {
            if ($file === '.' || $file === '..') {
                continue;
            }

            $sourceFile = $path_from.'/'.$file;
            $destinationFile = $path_to.'/'.str_replace('.stub', '.yaml', $file);

            if (is_file($sourceFile)) {
                if ($file === 'Chart.stub') {
                    // Don't overwrite Chart.yaml if it exists - preserve version information
                    // Chart.yaml will be updated by buildHelmChart() method
                    if (! is_file($destinationFile)) {
                        copy($sourceFile, $destinationFile);
                        $changes = true;
                    }
                } elseif ($file === 'values.stub') {
                    // Merge values.stub with existing values.yaml to add new configuration variables
                    // Check for both cases (values.yaml and Values.yaml)
                    $valuesYamlPath = $path_to.'/values.yaml';
                    if (! is_file($valuesYamlPath)) {
                        $valuesYamlPath = $path_to.'/Values.yaml';
                    }

                    if (is_file($valuesYamlPath)) {
                        $this->output->writeln('  <bg=blue;fg=black> INFO </> Merging new configuration variables from values.stub...');
                        $changes = $this->mergeValuesFile($sourceFile, $valuesYamlPath) || $changes;
                    } else {
                        copy($sourceFile, $destinationFile);
                        $this->valuesFileCreated = true;
                        $changes = true;
                    }
                } else {
                    // For other files (templates), copy if different
                    if (! is_file($destinationFile) || hash_file('sha256', $sourceFile) !== hash_file('sha256', $destinationFile)) {
                        copy($sourceFile, $destinationFile);
                        $changes = true;
                    }
                }
            }
        }

        return $changes;
    }

    /**
     * Build the Helm Chart.
     *
     * @param  bool  $updateVersion  Whether to update the version (default: true)
     * @return void
     */
    protected function buildHelmChart(bool $updateVersion = true)
    {
        $this->output->writeln('  <bg=blue;fg=black> INFO </> Updating Chart.yaml...');

        $chartPath = $this->helmPath.'/Chart.yaml';
        $chart = Yaml::parseFile($chartPath);
        $chart['name'] = $this->projectName;

        // Only update version if requested (preserve if already updated before build)
        if ($updateVersion) {
            $chart['version'] = config('sail.build.version', '1.0.0');
            $chart['appVersion'] = config('sail.build.version', '1.0.0');
        }

        $chart['description'] = $this->projectName.' Helm Chart';
        $chart['maintainers'] = [
            [
                'name' => config('sail.build.organization', 'Laravel Sail'),
                'email' => config('mail.from.address', 'example@example.com'),
            ],
        ];

        $yaml = Yaml::dump($chart, Yaml::DUMP_OBJECT_AS_MAP);

        file_put_contents($chartPath, $yaml);
        $this->output->writeln('');
    }

    /**
     * Build the Helm Values.yaml file.
     *
     * @param  bool  $updateVersion  Whether the image tag may be updated (default: true)
     * @return void
     */
    protected function buildHelmValues(bool $updateVersion = true)
    {
        $this->output->writeln('  <bg=blue;fg=black> INFO </> Updating values.yaml...');
        // Check for both cases (Values.yaml and values.yaml)
        $valuesPath = $this->helmPath.'/values.yaml';
        if (! file_exists($valuesPath)) {
            $valuesPath = $this->helmPath.'/Values.yaml';
        }

        if (! $this->valuesFileCreated) {
            $this->updateExistingHelmValues($valuesPath, $updateVersion);

            return;
        }

        $values = Yaml::parseFile($valuesPath);

        $values['name'] = $this->projectName;

        $values['ingress']['hosts'][0]['host'] = config('sail.domain', "{$this->projectName}.test");

        $repository = config('sail.build.repository') ? config('sail.build.repository').'/' : '';
        $repository .= config('sail.build.organization') ? config('sail.build.organization').'/' : '';
        $repository .= Str::lower($this->projectName);

        $values['global']['tag'] = config('sail.build.version', 'latest');
        $values['web']['image']['repository'] = "{$repository}-web";
        $values['worker']['image']['repository'] = "{$repository}-worker";

        $values['secret']['path'] = config('sail.secret.path', "secret/laravel/{$this->projectName}");
        $values['secret']['store'] = config('sail.secret.store', 'vault-backend');

        $domains = explode(',', config('sail.deploy.domains', 'reyemtech.com'));
        foreach ($domains as $key => $domain) {
            $values['ingress']['hosts'][$key]['host'] = $domain;
            $values['ingress']['hosts'][$key]['paths'] = [
                [
                    'path' => '/',
                    'pathType' => 'Prefix',
                ],
            ];
        }

        // Add resource recommendations if not set
        if (empty($values['resources']) || (empty($values['resources']['requests']) && empty($values['resources']['limits']))) {
            $this->output->writeln('  <bg=yellow;fg=black> WARN </> No resource limits configured. Recommending defaults...');
            $recommendations = $this->recommendResources();
            $values['resources'] = $recommendations;
            $this->output->writeln('  <fg=green>✓</> Applied resource recommendations');
            $this->output->writeln('    Requests: CPU='.$recommendations['requests']['cpu'].', Memory='.$recommendations['requests']['memory']);
            $this->output->writeln('    Limits: CPU='.$recommendations['limits']['cpu'].', Memory='.$recommendations['limits']['memory']);
        }

        $yaml = Yaml::dump($values, Yaml::DUMP_OBJECT_AS_MAP);

        file_put_contents($valuesPath, $yaml);
        $this->output->writeln('');
    }

    /**
     * Update a pre-existing (consumer-owned) values.yaml without destroying it.
     *
     * Existing values always win and comments are preserved: the file is only
     * touched through targeted text edits (placeholder healing and, when the
     * caller asked for a version update, the global.tag scalar). If nothing
     * needs changing, the file is not rewritten at all.
     */
    protected function updateExistingHelmValues(string $valuesPath, bool $updateVersion): void
    {
        $text = file_get_contents($valuesPath);
        $original = $text;
        $values = Yaml::parse($text);
        $values = is_array($values) ? $values : [];

        $domains = explode(',', config('sail.deploy.domains', 'reyemtech.com'));

        // Heal stub placeholders if any survive in the existing file.
        $text = str_replace('<project-name>', $this->projectName, $text);
        $text = str_replace('<host>', $domains[0], $text);
        $text = str_replace('<path-to-secret>', config('sail.secret.path', "secret/laravel/{$this->projectName}"), $text);
        $text = str_replace('<secret-store-name>', config('sail.secret.store', 'vault-backend'), $text);

        $repository = config('sail.build.repository') ? config('sail.build.repository').'/' : '';
        $repository .= config('sail.build.organization') ? config('sail.build.organization').'/' : '';
        $repository .= Str::lower($this->projectName);

        foreach (['web', 'worker'] as $tier) {
            $current = $values[$tier]['image']['repository'] ?? null;

            if ($current === null || str_contains($current, '<')) {
                $text = $this->setYamlScalarInText($text, [$tier, 'image', 'repository'], "{$repository}-{$tier}");
            }
        }

        if ($updateVersion) {
            $text = $this->setYamlScalarInText($text, ['global', 'tag'], (string) config('sail.build.version', 'latest'));
        }

        if ($text !== $original) {
            file_put_contents($valuesPath, $text);
            $this->output->writeln('  <fg=green>✓</> Updated values.yaml (existing values and comments preserved)');
        } else {
            $this->output->writeln('  <fg=green>✓</> values.yaml unchanged (existing values and comments preserved)');
        }

        $this->output->writeln('');
    }

    /**
     * Recommend resource values based on app characteristics.
     */
    protected function recommendResources(): array
    {
        $appPath = base_path();
        $vendorSize = 0;
        $hasHorizon = file_exists($appPath.'/app/Console/Commands/HorizonCommand.php') ||
                      file_exists($appPath.'/config/horizon.php');

        // Estimate app size based on vendor directory
        if (is_dir($appPath.'/vendor')) {
            $vendorSize = $this->getDirectorySize($appPath.'/vendor');
        }

        // Base recommendations
        $cpuRequest = '100m';
        $memoryRequest = '256Mi';
        $cpuLimit = '500m';
        $memoryLimit = '512Mi';

        // Adjust based on app size
        if ($vendorSize > 100 * 1024 * 1024) { // > 100MB
            $memoryRequest = '512Mi';
            $memoryLimit = '1Gi';
        }

        // Adjust for Horizon (queue workers need more resources)
        if ($hasHorizon) {
            $cpuLimit = '1000m';
            $memoryLimit = '1Gi';
        }

        return [
            'requests' => [
                'cpu' => $cpuRequest,
                'memory' => $memoryRequest,
            ],
            'limits' => [
                'cpu' => $cpuLimit,
                'memory' => $memoryLimit,
            ],
        ];
    }

    /**
     * Get directory size in bytes.
     */
    protected function getDirectorySize(string $directory): int
    {
        $size = 0;
        if (is_dir($directory)) {
            $iterator = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($directory, \RecursiveDirectoryIterator::SKIP_DOTS)
            );
            foreach ($iterator as $file) {
                if ($file->isFile()) {
                    $size += $file->getSize();
                }
            }
        }

        return $size;
    }

    /**
     * Merge values.stub with existing values.yaml to add new configuration variables.
     *
     * The merge is purely additive and text-preserving: missing keys from the
     * stub are inserted into the consumer's file as text, so existing values,
     * ordering, and comments (including functional markers such as
     * `# x-release-please-version`) are never touched. Free-form maps the
     * consumer already owns (annotations, labels, etc.) are left alone.
     *
     * @param  string  $stubPath  Path to values.stub
     * @param  string  $valuesPath  Path to values.yaml
     * @return bool Returns true if changes were made
     */
    protected function mergeValuesFile(string $stubPath, string $valuesPath): bool
    {
        $stubValues = Yaml::parseFile($stubPath);
        $existingValues = Yaml::parseFile($valuesPath);

        if (! is_array($stubValues) || ! is_array($existingValues)) {
            return false;
        }

        $missing = $this->collectMissingValues($existingValues, $stubValues);

        if (empty($missing)) {
            return false;
        }

        $text = file_get_contents($valuesPath);
        $addedKeys = [];

        foreach ($missing as [$path, $value]) {
            $inserted = false;
            $text = $this->insertYamlKey($text, $path, $value, $inserted);

            if ($inserted) {
                $addedKeys[] = implode('.', $path);
            }
        }

        if (empty($addedKeys)) {
            return false;
        }

        file_put_contents($valuesPath, $text);

        $this->output->writeln('  <fg=green>✓</> Added new configuration variables from values.stub:');
        foreach ($addedKeys as $addedKey) {
            $this->output->writeln('    - '.$addedKey);
        }

        return true;
    }

    /**
     * Collect stub keys missing from the consumer's values.
     *
     * Existing keys always win — scalars are never overwritten, lists are
     * never merged into, and consumer-owned free-form maps (annotations and
     * friends) are never extended with stub defaults. When an entire subtree
     * is missing, one entry with the full subtree is returned.
     *
     * @param  array  $target  Existing values
     * @param  array  $source  Stub values
     * @param  array<int, string>  $path  Current key path (internal use)
     * @return array<int, array{0: array<int, string>, 1: mixed}> List of [path, value] additions
     */
    protected function collectMissingValues(array $target, array $source, array $path = []): array
    {
        $missing = [];

        foreach ($source as $key => $value) {
            $keyPath = array_merge($path, [(string) $key]);

            if (! array_key_exists($key, $target)) {
                $missing[] = [$keyPath, $value];
            } elseif (is_array($value) && is_array($target[$key])
                && ! in_array($key, $this->consumerOwnedMapKeys, true)
                && ! $this->isYamlList($value) && ! $this->isYamlList($target[$key])) {
                $missing = array_merge($missing, $this->collectMissingValues($target[$key], $value, $keyPath));
            }
        }

        return $missing;
    }

    /**
     * Determine whether a parsed YAML array is a sequence (list) rather than a map.
     */
    protected function isYamlList(array $value): bool
    {
        return $value === [] || array_keys($value) === range(0, count($value) - 1);
    }

    /**
     * Insert a missing key (with its subtree) into YAML text without
     * re-emitting the document, so existing content and comments survive.
     *
     * Top-level keys are appended to the end of the file; nested keys are
     * inserted at the end of their parent block with matching indentation.
     * If the parent cannot be located as a block map, the text is returned
     * unchanged and $inserted stays false.
     *
     * @param  string  $text  Original YAML text
     * @param  array<int, string>  $path  Full key path to insert
     * @param  mixed  $value  Parsed value for the key
     * @param  bool  &$inserted  Set to true when the insertion succeeded
     */
    protected function insertYamlKey(string $text, array $path, $value, bool &$inserted): string
    {
        $inserted = false;
        $key = $path[count($path) - 1];
        $parentPath = array_slice($path, 0, -1);

        $block = rtrim(Yaml::dump([$key => $value], 10, 2, Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK));

        if (empty($parentPath)) {
            $inserted = true;

            return rtrim($text, "\n")."\n\n".$block."\n";
        }

        $lines = explode("\n", $text);
        $parent = $this->findYamlKeyLine($lines, $parentPath);

        if ($parent === null) {
            return $text;
        }

        [$parentIndex, $parentIndent] = $parent;

        // Separate any inline value on the parent line from a trailing comment.
        $afterColon = substr($lines[$parentIndex], strpos($lines[$parentIndex], ':') + 1);
        $comment = '';
        if (preg_match('/(\s+#.*)$/', $afterColon, $match)) {
            $comment = $match[1];
            $afterColon = substr($afterColon, 0, -strlen($match[1]));
        }
        $inlineValue = trim($afterColon);

        // The parent must be a block map to append a child line. A flow-style
        // map (e.g. `service: { type: ClusterIP }`) still owns required stub
        // defaults, so expand it to a block map that includes the missing key
        // rather than dropping the key and rendering an invalid chart. Any
        // other inline value (a scalar or flow list) is a type mismatch we
        // leave untouched.
        if ($inlineValue !== '') {
            if ($inlineValue[0] !== '{') {
                return $text;
            }

            $existing = Yaml::parse($inlineValue);

            if (! is_array($existing) || $this->isYamlList($existing)) {
                return $text;
            }

            // Existing keys win; only the missing key is added.
            $merged = $existing + [$key => $value];
            $parentKey = $parentPath[count($parentPath) - 1];
            $expanded = rtrim(Yaml::dump([$parentKey => $merged], 10, 2, Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK));

            $expandedLines = explode("\n", $expanded);
            foreach ($expandedLines as $i => &$line) {
                if ($line === '') {
                    continue;
                }
                $line = str_repeat(' ', $parentIndent).$line;
                if ($i === 0 && $comment !== '') {
                    $line .= $comment;
                }
            }
            unset($line);

            array_splice($lines, $parentIndex, 1, $expandedLines);
            $inserted = true;

            return implode("\n", $lines);
        }

        [$insertAfter, $childIndent] = $this->yamlBlockExtent($lines, $parentIndex, $parentIndent);

        $indentedBlock = array_map(function ($line) use ($childIndent) {
            return $line === '' ? '' : str_repeat(' ', $childIndent).$line;
        }, explode("\n", $block));

        array_splice($lines, $insertAfter + 1, 0, $indentedBlock);
        $inserted = true;

        return implode("\n", $lines);
    }

    /**
     * Locate the line holding the key at the given path.
     *
     * @param  array<int, string>  $lines  YAML text split into lines
     * @param  array<int, string>  $path  Key path to locate
     * @return array{0: int, 1: int}|null [line index, indent] or null when not found
     */
    protected function findYamlKeyLine(array $lines, array $path): ?array
    {
        $start = 0;
        $end = count($lines);
        $parentIndent = -1;
        $lastSegment = count($path) - 1;

        foreach ($path as $depth => $segment) {
            $levelIndent = null;
            $foundIndex = null;

            for ($i = $start; $i < $end; $i++) {
                $trimmed = ltrim($lines[$i]);

                if ($trimmed === '' || $trimmed[0] === '#') {
                    continue;
                }

                $indent = strlen($lines[$i]) - strlen($trimmed);

                if ($indent <= $parentIndent) {
                    break;
                }

                if ($levelIndent === null) {
                    $levelIndent = $indent;
                }

                if ($indent === $levelIndent && $this->yamlLineMatchesKey($trimmed, $segment)) {
                    $foundIndex = $i;
                    break;
                }
            }

            if ($foundIndex === null || $levelIndent === null) {
                return null;
            }

            if ($depth === $lastSegment) {
                return [$foundIndex, $levelIndent];
            }

            $start = $foundIndex + 1;
            $parentIndent = $levelIndent;

            for ($i = $start; $i < $end; $i++) {
                $trimmed = ltrim($lines[$i]);

                if ($trimmed === '') {
                    continue;
                }

                if ((strlen($lines[$i]) - strlen($trimmed)) <= $parentIndent) {
                    $end = $i;
                    break;
                }
            }
        }

        return null;
    }

    /**
     * Determine the extent of a block map for insertion purposes.
     *
     * @param  array<int, string>  $lines  YAML text split into lines
     * @param  int  $parentIndex  Line index of the parent key
     * @param  int  $parentIndent  Indent of the parent key
     * @return array{0: int, 1: int} [last content line of the block, child indent]
     */
    protected function yamlBlockExtent(array $lines, int $parentIndex, int $parentIndent): array
    {
        $lastContent = $parentIndex;
        $childIndent = null;
        $total = count($lines);

        for ($i = $parentIndex + 1; $i < $total; $i++) {
            $trimmed = ltrim($lines[$i]);

            if ($trimmed === '') {
                continue;
            }

            $indent = strlen($lines[$i]) - strlen($trimmed);

            if ($indent <= $parentIndent) {
                break;
            }

            if ($childIndent === null && $trimmed[0] !== '#') {
                $childIndent = $indent;
            }

            $lastContent = $i;
        }

        return [$lastContent, $childIndent ?? $parentIndent + 2];
    }

    /**
     * Determine whether a trimmed YAML line declares the given key.
     */
    protected function yamlLineMatchesKey(string $trimmedLine, string $key): bool
    {
        $quoted = preg_quote($key, '/');

        return (bool) preg_match('/^(?:'.$quoted.'|"'.$quoted.'"|\''.$quoted.'\')\s*:/', $trimmedLine);
    }

    /**
     * Replace the scalar value of the key at the given path in YAML text,
     * preserving indentation and any trailing inline comment (such as the
     * `# x-release-please-version` marker release automation relies on).
     *
     * @param  array<int, string>  $path  Key path whose scalar should be replaced
     */
    protected function setYamlScalarInText(string $text, array $path, string $value): string
    {
        $lines = explode("\n", $text);
        $located = $this->findYamlKeyLine($lines, $path);

        if ($located === null) {
            return $text;
        }

        [$index] = $located;

        if (preg_match('/^(\s*(?:"[^"]+"|\'[^\']+\'|[^:#]+?)\s*:\s*)([^#]*?)(\s*#.*)?$/', $lines[$index], $matches)) {
            if (trim($matches[2]) === '') {
                // Key holds a nested block, not a scalar — leave it alone.
                return $text;
            }

            $lines[$index] = $matches[1].$value.($matches[3] ?? '');
        }

        return implode("\n", $lines);
    }
}
